/*DROP*
 DROP TABLE IF EXISTS invoice_detail;
 DROP TABLE IF EXISTS invoice;
 DROP TABLE IF EXISTS client;
 DROP TABLE IF EXISTS discount;
 DROP TABLE IF EXISTS type;
 DROP TABLE IF EXISTS product;
 DROP TABLE IF EXISTS category;
 /*CREATE*/
CREATE TABLE IF NOT EXISTS category (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);
CREATE TABLE IF NOT EXISTS product (
    "id" SERIAL PRIMARY KEY,
    "categoryId" INT,
    "name" VARCHAR(100) NOT NULL,
    "price" NUMERIC NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY(categoryId) REFERENCES category(id)
);
CREATE TABLE IF NOT EXISTS type (
    "id" SERIAL PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
);
CREATE TABLE IF NOT EXISTS discount (
    "id" SERIAL PRIMARY KEY,
    "typeId" INT,
    "percent" NUMERIC NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_discount_type FOREIGN KEY(typeId) REFERENCES type(id)
);
CREATE TABLE IF NOT EXISTS client (
    "id" SERIAL PRIMARY KEY,
    "typeId" INT,
    "name" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_client_type FOREIGN KEY(typeId) REFERENCES type(id)
);
CREATE TABLE IF NOT EXISTS invoice (
    "id" SERIAL PRIMARY KEY,
    "clientId" INT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoice_client FOREIGN KEY(clientId) REFERENCES client(id)
);
CREATE TABLE IF NOT EXISTS invoice_detail (
    "id" SERIAL PRIMARY KEY,
    "invoiceId" INT,
    "discountId" INT,
    "productId" INT,
    "quantity" INT,
    "price" NUMERIC NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_detail_invoice FOREIGN KEY(invoiceId) REFERENCES invoice(id),
    CONSTRAINT fk_detail_discount FOREIGN KEY(discountId) REFERENCES discount(id),
    CONSTRAINT fk_detail_product FOREIGN KEY(productId) REFERENCES product(id)
);